platform :ios do
  lane :screenshots do
    retrofit_cordova_screenshots_ios(
      team_id: "[YOUR TEAM ID]",
      bundle_id: "[YOUR APP BUNDLE ID]"
    )
    snapshot(
      output_simulator_logs: true,
      reinstall_app: false,
      erase_simulator: true,
      scheme: "ionic-screen-shots" # TODO
    )
  end
end

platform :android do
  lane :screenshots do
    retrofit_cordova_screenshots_android
    gradle(
      task: 'assemble',
      build_type: 'Debug',
      project_dir: 'platforms/android'
    )
    gradle(
      task: 'assemble',
      build_type: 'AndroidTest',
      project_dir: 'platforms/android'
    )
    screengrab
  end
end
