require 'fastlane/plugin/cordova_screenshots/constants'

module Fastlane
  module Helper
    class CordovaScreenshotsHelper
      HELPER_PATH = File.expand_path(File.dirname(__FILE__))

      def self.copy_all_files(src_folder, project_folder)
        if src_folder && Dir.exist?(src_folder)
          dest_folder = project_folder.to_s
          UI.message "Copying all files from '#{src_folder}' to '#{dest_folder}'"
          Dir.exist?(dest_folder) || FileUtils.mkdir_p(dest_folder)
          FileUtils.cp_r(src_folder + "/.", dest_folder)
        elsif
          UI.user_error! "Copying files: '#{src_folder}' does not exist."
        end
      end

      def self.copy_ios_sample_tests(scheme_name)
        ios_resources_path = File.expand_path("#{HELPER_PATH}/../resources/ios")
        source_folder = "#{ios_resources_path}/#{CordovaScreenshots::IONIC_DEFAULT_UNIT_TEST_NAME}"
        dest_folder = "#{CordovaScreenshots::IONIC_IOS_CONFIG_PATH}/#{scheme_name}"
        copy_all_files(source_folder, dest_folder)
      end

      #
      # Find any existing Xcode Workspace generated by Cordova/Ionic
      #
      def self.find_default_ios_xcode_workspace
        Dir["#{CordovaScreenshots::IONIC_IOS_BUILD_PATH}/*.xcodeproj"].last || nil
      end
    end
  end
end
